
CC = g++
CFLAGS = -c
EFLAGS=-o

all: nodo tree pruebadupla 

nodo: nodo2.hpp
	$(CC) $(CFLAGS) nodo2.hpp 
	
tree:
	$(CC) $(CFLAGS) arbol.hpp
	
pruebadupla: pruebadupla.cpp
	$(CC) $(EFLAGS) dupla.exe  pruebadupla.cpp


